# Generated by Django 4.2.4 on 2023-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, unique=True, verbose_name='Password')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('soName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['email'],
            },
        ),
    ]
