# Generated by Django 4.2.4 on 2023-08-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='muusers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
